### ISSUE TITLE
Update and adjust the palette mockups

### ISSUE THREAD

**Issue by LoweLeo** [selsa-inube/isetting#511]
The palette selection screens are updated to add the selection of Alpha Neutral colors

![imagen](https://github.com/selsa-inube/linpar/assets/152199887/aac5a38c-aea8-40e8-88be-b10d9907b7c3)

Additionally, the size of the field where the token goes is modified, so that it is aligned with the neutral alpha

![imagen](https://github.com/selsa-inube/linpar/assets/152199887/4f7e069b-98d2-44db-ad60-24a32fb5e063)
![imagen](https://github.com/selsa-inube/linpar/assets/152199887/17e93a3e-414b-4398-b9bf-a7da2b7e63e4)

**Comment by cmarin001** [comment]
this issue was attended
