### ISSUE TITLE
Fix: Adjust <SendInformationMessage/> in order to assure handling  for the tokens along the app

### ISSUE THREAD

**Issue by cmarin001** [selsa-inube/isetting#554]
We need to ensure that the <SendInformationMessage/> function accounts for all varieties of tokens. Currently, it only recognizes surface-tokens, but it lacks support for stroke tokens. This oversight leads to application crashes when an unrecognized token value is received

![image](https://github.com/selsa-inube/linpar/assets/45011420/6b3226aa-2df5-4cd8-80ad-4a72d60b381d)

![image](https://github.com/selsa-inube/linpar/assets/45011420/8957c903-6c10-40b5-9c44-5a16b67cd5e1)

**Comment by carin91** [comment]
This task should be reconsidered, evaluating the <Lines/> behavior presented in the wirefrimes i could conclude that the apperance is not changing, however, the type of <Button/> from "filled" to "outlined" and nothing else.

However, i think we need an additional wirefrime for the divisor tab in lines.

This activity will not be completed until the merging for the activities 607,608,610.
