### ISSUE TITLE
Changing between menu tabs triggers an unintended logout

### ISSUE THREAD

**Issue by carin91** [selsa-inube/isetting#569]
When to click several times the menu tabs...
![image](https://github.com/selsa-inube/linpar/assets/123512032/49308921-98f6-4e2e-a4b4-75d6b53b3522)

...the app logout 
![image](https://github.com/selsa-inube/linpar/assets/123512032/bcb8978b-6a59-4a0f-b80c-5c673f1035ad)

**Comment by cmarin001** [comment]
this issue was attended
