### ISSUE TITLE
Refactor the renderMessage function/component

### ISSUE THREAD

**Issue by carin91** [selsa-inube/isetting#579]
We are defining a renderMessage function, closeMessageAndExcecuteCallback function, handlecloseMessageFunction and a onMessageClosed function in at least 3-7 components, including parent components Text, Palette, Strokes and Surfaces, as in their form children

Refactor the App to create all of this set of functions and import it into all of the components which need it. I assumed that the only components needing this are the forms.

**Comment by cmarin001** [comment]
This issue was attended on SET683
