### ISSUE TITLE
Including tokens from different clients

### ISSUE THREAD

**Issue by carin91** [selsa-inube/isetting#580]
As you can see in "Personas" the tokens of different clients were mocked.

![image](https://github.com/selsa-inube/linpar/assets/123512032/0c773a01-b4b8-4078-b9d7-bb093bbbefa3)

This information could be included to enhance the iSetting mocked of some clients: {cooservunal, corbanca, fondecom, presente?}

**Comment by cmarin001** [comment]
this issue was attended
