### ISSUE TITLE
Token color palette does not match figma design

### ISSUE THREAD

**Issue by carin91** [selsa-inube/isetting#589]
The padding-right of the renderCategoryGrid does not match the padding-right presenten in figma design:

Wireframes:
![image](https://github.com/selsa-inube/isetting/assets/123512032/39a63ed5-b272-4589-8e55-501f1a36e840)

iSetting
![image](https://github.com/selsa-inube/isetting/assets/123512032/75534428-265a-4084-84f0-bc08826e24e3)

It happens for all of the screen sizes.

**Comment by cmarin001** [comment]
This issue was attended on SET681
