### ISSUE TITLE
The storybook is not working in Clients or in loading-app:

### ISSUE THREAD

**Issue by LinconOssa** [selsa-inube/isetting#592]
The storybook is not working in Clients or in loading-app:
![image](https://github.com/selsa-inube/isetting/assets/103295353/1e238631-99f7-44f1-a918-f80e01493dc4)
![image](https://github.com/selsa-inube/isetting/assets/103295353/fddb289c-1b1c-4695-b206-914fdce41db2)

_Originally posted by @LinconOssa in https://github.com/selsa-inube/isetting/pull/573#pullrequestreview-1865776766_

**Comment by cmarin001** [comment]
This issue was attended SET689
