### ISSUE TITLE
Create a Color folder into people/outlets grouping the color blocks.

### ISSUE THREAD

**Issue by carin91** [selsa-inube/isetting#601]
With the fonts enhancement it was necessary to redistribute the folders in the storybook and the app directory.

![image](https://github.com/selsa-inube/isetting/assets/123512032/3da5f642-b69a-4c72-8de0-ab78cd657e07)
![image](https://github.com/selsa-inube/isetting/assets/123512032/8b8c91a9-f833-4fca-a713-8d468373ef40)

As you can see, the fonts and other typography blocks could be group by their domain (typography). The color blocks should be group by its domain "color" through the creation of a the color folder and moving all of the color blocks into it.

Be to verify all of the imports related to these components.

**Comment by cmarin001** [comment]
This issue was attended on SET686
