### ISSUE TITLE
Solve the problem with the Token

### ISSUE THREAD

**Issue by LinconOssa** [selsa-inube/isetting#632]
The token must be updated when the user modifies it and saves the changes, thus ensuring precise synchronization between the interface and the underlying information. However, it is important to note that this token update should not affect the associated color palette. That is, even if changes are made to the token, the color palette must remain unchanged, maintaining visual consistency and user experience.

This separation of token and color palette updating ensures efficient management of customization and configuration by the user, without compromising the aesthetic coherence of the interface. Additionally, this distinction allows for greater flexibility and adaptability in design, as changes to the token can be reflected dynamically without affecting other predefined visual aspects.

![image](https://github.com/selsa-inube/isetting/assets/103295353/347e64c9-2008-46ae-b6ee-c8dbc7e64246)

**Comment by carin91** [comment]
solve in the set735
