### ISSUE TITLE
Adjust the location for submit buttons into the initializerForm component

### ISSUE THREAD

**Issue by carin91** [selsa-inube/isetting#662]
The submit buttons in the initializerForm are misplaced. 
![image](https://github.com/selsa-inube/isetting/assets/123512032/99acccf6-fcb0-4795-ba87-6f443f67de96)

**Comment by Andresbl123** [comment]
I think this can be solved by removing the `heigth: 100vh` property in the fomr, as it causes the height of the graphic window to be broken.
![image](https://github.com/selsa-inube/isetting/assets/74839801/c7fc5580-dc6e-454d-bea5-100a5353dacd)
![image](https://github.com/selsa-inube/isetting/assets/74839801/ed4f1db3-0db6-4194-b812-ea9f31320f05)
![image](https://github.com/selsa-inube/isetting/assets/74839801/c7f23d23-e8ed-4f82-9884-c5855b87a103)
